### ISSUE TITLE
Registers completion provider only for language opened at startup

### ISSUE THREAD

**Issue by inosik** [Sammons/pluggable-autocomplete#1]
The completions are only provided for the language which was in [the first opened file][code] at the startup of VS Code.

  [code]: https://github.com/Sammons/pluggable-autocomplete/blob/31c0a48cd9fc2607427e1834255aa3200dcc2070/src/resolver.ts#L63

Steps to reproduce:

1. Create the sample plugin
1. Open any file, e. g. a JavaScript file
1. Reload window

   *Example items are provided for JS files only.*

1. Open file containing another language, e. g. a CSS file
1. Reload window

   *Example items are provided for CSS files only.*

**Comment by Sammons** [comment]
Pushed in 0.1.0 - sorry for the long time out of action, but this is in now!
