### ISSUE TITLE
reading completions from file

### ISSUE THREAD

**Issue by semiversus** [Sammons/pluggable-autocomplete#2]
pluggable-autocomplete is the nearest I could get to have my wish fulfilled. I'm searching for a tool which is reading the completions from a file (may be configurable or fixed to e.g. .completions). The completion file could be created with whatever tool or programming language you want.

May be it's an idea for a plugin to pluggable-autocomplete or an extension by itself.

**Comment by Sammons** [comment]
I wrote pluggable autocomplete to autocomplete table names live from a local postgres database, so we can definitely get closer to what you want. I'll look at adapting it to read a .json file sometime soon, but it is not a big change.

**Comment by semiversus** [comment]
Would be awesome!

**Comment by Sammons** [comment]
@semiversus added in 0.1.0, available now. Take a look and let me know how it works for you! the readme describes the shape of the file, but you can effectively have a setting `pluggableautocomplete.json` point to `~/plugs.json` (or wherever you like) with 
```{ "name": "plugins", "items": [{"value": "something", "comment": "should work"}] }```
 inside the file.

**Comment by semiversus** [comment]
Cool, will make a script for my use case and will report you the next days!

**Comment by Sammons** [comment]
@semiversus did this do what you wanted? Going to resolve for now.

**Comment by semiversus** [comment]
Hi @Sammons, yes it's working as wanted. I'm using it succesfully. Thanks for your work!
