### ISSUE TITLE
Currently the plugin has only 1 name- Can you make it to multiple in plug.json

### ISSUE THREAD

**Issue by skandasoft** [Sammons/pluggable-autocomplete#3]
Hi, Thanks for the awesome plugin.

Currently the plugin.json has only 1 name/items attribute. The way I use it is as name/values dropdown.
I type the name and get name. values in the editor.
But this allows for only 1 name/values. which means I can have autocomplete for only 1 word.
Can you make it to multiple in plug.json

**Comment by Sammons** [comment]
Sure let me take a look

**Comment by Sammons** [comment]
@skandasoft I published 1.0, in it I deprecated the name field. Just put `{ "items": [{value: "something"}] }` and it should only complete that value. Let me know if that's not the behavior you want.
